import React, { useState } from 'react';
import { 
  ShieldCheck, 
  Lock, 
  CheckCircle2 
} from 'lucide-react';
import { GuardrailPolicy } from '../types';

interface GuardrailsPanelProps {
  guardrails: GuardrailPolicy[];
  onUpdateGuardrail: (updated: GuardrailPolicy[]) => void;
}

export const GuardrailsPanel: React.FC<GuardrailsPanelProps> = ({
  guardrails,
  onUpdateGuardrail,
}) => {
  const [policies, setPolicies] = useState<GuardrailPolicy[]>(guardrails);
  const [hasChanges, setHasChanges] = useState<boolean>(false);

  const togglePolicy = (id: string) => {
    const updated = policies.map(p => {
      if (p.id === id) {
        return { ...p, enabled: !p.enabled };
      }
      return p;
    });
    setPolicies(updated);
    setHasChanges(true);
  };

  const handleValueChange = (id: string, newVal: any) => {
    const updated = policies.map(p => {
      if (p.id === id) {
        return { ...p, value: newVal };
      }
      return p;
    });
    setPolicies(updated);
    setHasChanges(true);
  };

  const handleSave = () => {
    onUpdateGuardrail(policies);
    setHasChanges(false);
  };

  return (
    <div id="guardrails-panel-view" className="space-y-6">
      {/* Top Banner */}
      <div className="p-5 border border-[#27272A] bg-[#121215] flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-sm font-black uppercase font-mono tracking-wider text-white flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-[#00F0FF]" />
            <span>Enterprise Guardrails & Model Armor Security Firewall</span>
          </h2>
          <p className="text-[11px] font-mono text-[#888] mt-0.5">
            Deterministic boundaries enforcing blast-radius limits, FinOps budget ceilings, and zero-trust cryptographic signature verification
          </p>
        </div>

        {hasChanges && (
          <button
            onClick={handleSave}
            className="flex items-center gap-1.5 px-4 py-2 bg-[#00F0FF] text-black font-mono font-bold text-xs uppercase tracking-wider shadow-[0_0_10px_#00F0FF] transition-all cursor-pointer"
          >
            <CheckCircle2 className="w-3.7 h-3.7" />
            <span>Apply Guardrail Updates</span>
          </button>
        )}
      </div>

      {/* Model Armor Core Security Card */}
      <div className="p-5 border border-emerald-500/40 bg-emerald-950/20 space-y-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Lock className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-white">Google Model Armor Semantic Firewall: LOCKED</span>
          </div>
          <span className="px-2 py-0.5 text-[9px] font-mono font-bold uppercase tracking-wider bg-emerald-950 text-emerald-300 border border-emerald-500/40">
            Zero-Trust Enforced
          </span>
        </div>
        <p className="text-xs font-mono text-[#CCC] leading-relaxed">
          Model Armor intercepts every candidate tool invocation generated by Gemini before API transmission. Parameters exceeding the maximum replica threshold or requesting unauthenticated subnet bans are automatically stripped and flagged for manual SRE cryptographic override.
        </p>
      </div>

      {/* Policy Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {policies.map((policy) => {
          return (
            <div 
              key={policy.id}
              className={`p-5 border transition-all flex flex-col justify-between ${
                policy.enabled 
                  ? 'bg-[#121215] border-[#27272A]' 
                  : 'bg-[#0E0E10] border-[#1F1F22] opacity-50'
              }`}
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-2 py-0.5 text-[9px] font-mono font-bold uppercase tracking-wider bg-[#1A1A1E] border border-[#27272A] text-[#888]">
                    {policy.category}
                  </span>

                  <div className="flex items-center gap-2 font-mono">
                    {policy.lockedByModelArmor && (
                      <span className="flex items-center gap-1 text-[9px] text-emerald-400">
                        <Lock className="w-3 h-3" />
                        LOCKED
                      </span>
                    )}

                    {/* Enable Toggle Switch */}
                    <button
                      onClick={() => togglePolicy(policy.id)}
                      className={`relative inline-flex h-4 w-8 items-center rounded-none transition-colors cursor-pointer border ${
                        policy.enabled ? 'bg-[#00F0FF] border-[#00F0FF]' : 'bg-[#27272A] border-[#444]'
                      }`}
                    >
                      <span
                        className={`inline-block h-2.5 w-2.5 transform bg-black transition-transform ${
                          policy.enabled ? 'translate-x-4' : 'translate-x-0.5'
                        }`}
                      />
                    </button>
                  </div>
                </div>

                <div>
                  <h4 className="text-xs font-bold text-white uppercase font-mono tracking-wider">{policy.name}</h4>
                  <p className="text-[11px] text-[#888] mt-1 leading-relaxed font-mono">{policy.description}</p>
                </div>
              </div>

              {/* Policy Threshold Config */}
              <div className="mt-4 pt-3 border-t border-[#27272A] flex items-center justify-between font-mono">
                <span className="text-[10px] text-[#888] uppercase">Configured Boundary:</span>
                <div className="flex items-center gap-1.5">
                  {typeof policy.value === 'number' ? (
                    <div className="flex items-center gap-1 font-mono text-xs font-bold text-[#00F0FF]">
                      <input
                        type="number"
                        value={policy.value}
                        onChange={(e) => handleValueChange(policy.id, parseFloat(e.target.value) || 0)}
                        className="w-16 bg-black border border-[#27272A] px-1.5 py-0.5 text-right text-[#00F0FF] focus:outline-none focus:border-[#00F0FF]"
                      />
                      <span className="text-[10px] text-[#888]">{policy.unit}</span>
                    </div>
                  ) : (
                    <span className="font-mono text-xs font-bold text-[#00F0FF] bg-black px-2 py-0.5 border border-[#27272A]">
                      {policy.value}
                    </span>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
